#!/usr/bin/env python3

# Copyright (c) 2019 Anton Semjonov
# Licensed under the MIT License

import subprocess, csv, tempfile, sys, argparse, os, io
import dateutil.parser
import dataset

# default / environment variables
DATABASE = os.environ.get("DATABASE", "sqlite:////data/speedtest.db")
PORT = os.environ.get("PORT", "8000")
SERVERID = os.environ.get("SERVERID", None)

# commandline parser
p = argparse.ArgumentParser()
p.add_argument("-d", dest="database", help="database connection uri (env:DATABASE)", default=DATABASE)
p.add_argument("-p", dest="port", help="port to run application server on (env:PORT)", default=PORT)
p.add_argument("-l", dest="limit", help="limit number of results when dumping", default=32768)
p.add_argument("-a", dest="after", help="start dump after this date", default=None)
p.add_argument("-s", dest="serverid", help="take measurements against specific speedtest.net server", default=SERVERID)
p.add_argument("--debug", help="enable flask debugging", action="store_true")
p.add_argument("command", choices=["serve", "measure", "dump", "import"], help="start webserver, take a measurement, dump results to csv or reimport csv data")
args = p.parse_args()

# connect to database
db = dataset.connect(args.database)
table = db["speedtest"]

# run a command and capture output
def run(cmd, stdin=None):
  return subprocess.run(cmd, capture_output=True, stdin=stdin)

# csv column names
FIELDNAMES = ("Server ID", "Sponsor", "Server Name", "Timestamp", "Distance", "Ping", "Download", "Upload", "Share", "IP Address")

# parse csv results from speedtest-cli to dicts
def parse_measurements(f):
  cr = csv.DictReader(f, fieldnames=FIELDNAMES)
  for line in cr:
    if list(line.values()) == list(FIELDNAMES):
      continue # skip header
    yield line

# output stored database rows as spooled csv file with header
def csvout(rows):
  f = tempfile.SpooledTemporaryFile(mode="wt+")
  wr = csv.DictWriter(f, fieldnames=FIELDNAMES)
  wr.writeheader()
  for row in sorted(rows, key=lambda r: r["id"]):
    del row["id"]
    wr.writerow(row)
  f.seek(0)
  return f

# take a new measurement with speedtest-cli
def take_measurement():
  cmd = ["speedtest-cli", "--csv"]
  if args.serverid: cmd += ["--server", args.serverid]
  res = run(cmd)
  if res.returncode != 0:
    print(res.stderr, file=sys.stderr)
  r = next(parse_measurements(io.StringIO(res.stdout.decode())))
  table.insert(r)
  print(r)

# import measurements from stdin
def import_measurements(f):
  for line in parse_measurements(f):
    print(line)
    table.insert(line)

# retrieve measurements from table applying optional filters
def retrieve_measurements(limit, after):

  # maybe use a query to filter by timestamp
  if after:
    try: after = dateutil.parser.parse(after).isoformat()
    except Exception as e:
      raise ValueError("cannot parse argument as date: " + str(e))
    return db.query("SELECT * FROM speedtest WHERE \"Timestamp\" >= :ts ORDER BY \"Timestamp\" ASC LIMIT :li", ts=after, li=limit)
  else:
    return db.query("SELECT * FROM speedtest WHERE \"Timestamp\" IS NOT NULL ORDER BY \"Timestamp\" DESC LIMIT :li", li=limit)

# just return the total number of rows
def total_measurements():
  return len(table)

def flask_server():

  # initialize flask
  import flask
  print(" * Connected database: {}".format(args.database))
  app = flask.Flask("speedtest", root_path="./")
  app.env = "development"

  # retrieve request parameters for retrieval
  def request_params(request, limit=1344): # ~ two weeks with a 15 min timer
    limit = flask.request.args.get("limit", None) or limit
    after = flask.request.args.get("after", None)
    return (limit, after)

  # scale number as mbit/s
  @app.template_filter("mbits")
  def to_mbits(d, fact=1_000_000, unit="MBit/s"):
    scaled = float(d) / fact
    return f"{scaled:.2f} {unit}"

  # homepage with rendered results
  @app.route("/")
  def home():
    try:
      limit, after = request_params(flask.request)
      rows = retrieve_measurements(limit, after)
      rows = [r for r in rows]
      last = rows[0]
      total = total_measurements()

      TEMPLATE = """
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <title>Speedtest Plot</title>
            <style>
              input {
                box-sizing: border-box;
                border: 1px solid #000;
                border-radius: 3px;
                padding: 0.5em;
              }
              html {
                font-family: monospace;
              }
              img {
                border: 1px solid black;
                margin: 1em;
                max-width: calc(100% - 2em);
              }
            </style>
          </head>
          <body>
            <center>
              <form action="/" method="get">
                Limit: <input type="number" name="limit" value="{{ limit }}" title="limit to n results">
                / <span title="total number of measurements">{{ total }}</span>,
                After: <input type="text" name="after" value="{{ after }}" title="limit to results after this date">
                <input type="submit" value="Apply">
              </form>
              <p>
                Measurement at {{ last['Timestamp'] }} to {{ last['Sponsor'] }} ({{ last['Server ID'] }})<br>
                Download: {{ last['Download'] | mbits }},
                Upload: {{ last['Upload'] | mbits }},
                Ping: {{ "%.1f" | format( last['Ping'] | float ) }} ms
              </p>
              <a href="/results.csv?limit={{ limit }}&after={{ after }}">
                {% if rows < 2 %}
                <span>Not enough measurements for a plot (yet). Here's a CSV instead.</span>
                {% else %}
                <img src="/results.png?limit={{ limit }}&after={{ after }}">
                {% endif %}
              </a>
            </center>
          </body>
        </html>
      """
      return flask.render_template_string(TEMPLATE, args=flask.request.args, last=last, total=total, limit=limit, after=after or "", rows=len(rows))
    except Exception as e:
      err = str(e)
      if "no such table: speedtest" in err:
        err = "No measurements taken yet!\n" + err
      print(err)
      return flask.Response(err, mimetype="text/plain", status=500)

  # return rendered plot picture
  @app.route("/results.png")
  def render():
    try:
      limit, after = request_params(flask.request)
      rows = retrieve_measurements(limit, after)
      data = csvout(rows)
      plot = run(["gnuplot", "-c", "plotscript", "/dev/stdin", "/dev/stdout"], stdin=data)
      data.close()
      if plot.returncode != 0:
        raise ValueError(plot.stderr.decode())
      return flask.Response(plot.stdout, mimetype="image/png")
    except Exception as e:
      return flask.Response(str(e), mimetype="text/plain", status=500)

  # return raw data in formatted csv
  @app.route("/results.csv")
  def results():
    try:
      limit, after = request_params(flask.request, 32768) # 2^15 and a little more than a year with a 15 min timer
      rows = retrieve_measurements(limit, after)
      data = csvout(rows)
      out = data.read()
      data.close()
      return flask.Response(out, mimetype="text/plain")
    except Exception as e:
      return flask.Response(str(e), mimetype="text/plain", status=500)

  app.run(threaded=False, port=args.port, host="0.0.0.0", debug=args.debug)

# ---------- main() ----------
try:
  if args.command == "serve":
    flask_server()
  elif args.command == "measure":
    take_measurement()
  elif args.command == "import":
    import_measurements(sys.stdin)
  else:
      rows = retrieve_measurements(args.limit, args.after)
      data = csvout(rows)
      print(data.read(), end="")
      data.close()
except Exception as e:
  print(e)
  exit(1)
