name: devel

on:
  push:
    branches:
      - devel

env:
  PLATFORMS: linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64,linux/ppc64le

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.7.0

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./container/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: false
