name: pr

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened

env:
  PLATFORMS: linux/amd64

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2.3.5
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./container/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: false
